#!/usr/bin/env python3
"""Work out a PvZ2 mod's total level count by reading its OBB directly.

    python3 build_worlds.py com.ea.game.pvz2_cld

Writes worlds/<pkg>.json with an OBB fingerprint (source + size). ci.py
compares that fingerprint every run, so a mod update regenerates the counts
instead of silently keeping stale ones.

Counting rules, verified against the numbers the game's world map shows:
  - a world counts when Hidden == false in PACKAGES/WORLDMAPLIST.RTON
  - a level counts when m_eventType == 'level' AND m_dataString does NOT
    contain 'dangerroom' (see la_danger_room)
"""
import argparse
import json
import re
import os
import sys

from rsb import RSB, AdbReader, FileReader, HttpReader
from adb_util import find_adb, pick_device, sh

HERE = os.path.dirname(os.path.abspath(__file__))
WORLDS_DIR = os.path.join(HERE, 'worlds')


def la_danger_room(e):
    """Is this node a Danger Room, i.e. one the game leaves out of the count.

    Judged by m_dataString (the level file the node points at) rather than
    m_levelNodeType. Reflourished mislabels its carnival danger room as
    'normal' yet the game still excludes it. Testing for an empty
    m_displayText breaks elsewhere: Collided's lc_zomboss is empty too but is
    a real level. This rule matched all 6 numbers read off the game UI.
    """
    return 'dangerroom' in re.sub(r'[^a-z0-9]', '',
                                  str(e.get('m_dataString', '')).lower())


def _url_size(url):
    """Content-Length of the remote file, used as the OBB fingerprint."""
    import urllib.request
    from compat import UA
    try:
        req = urllib.request.Request(url, headers={'User-Agent': UA})
        req.get_method = lambda: 'HEAD'
        with urllib.request.urlopen(req, timeout=60) as r:
            return int(r.headers.get('Content-Length') or 0)
    except Exception:
        return 0


def obb_info(adb, dev, pkg):
    """(path, size, mtime) of the installed OBB."""
    out = sh(adb, 'shell', f"ls -1 /sdcard/Android/obb/{pkg}/*.obb 2>/dev/null",
             serial=dev, check=False).strip()
    paths = [p for p in out.splitlines() if p.strip().endswith('.obb')]
    if not paths:
        sys.exit(f'No OBB for {pkg} on device {dev}.')
    path = paths[0].strip()
    st = sh(adb, 'shell', f"stat -c '%s %Y' '{path}'", serial=dev).split()
    return path, int(st[0]), int(st[1])


def build(reader, fingerprint):
    rsb = RSB(reader)
    ml = rsb.rton('Packages', 'WORLDMAPLIST.RTON')['objects'][0]['objdata']['MapList']
    have = rsb.rsgs()

    worlds, order = {}, 0
    for m in ml:
        nm = m['MapName']
        key = 'WORLDPACKAGES_' + nm.upper()
        if key not in have:
            continue                          # rift or utility map, no package
        if m.get('ComingSoon') or m.get('Disabled'):
            continue
        od = rsb.rton(key, 'WORLDMAP.RTON')['objects'][0]['objdata']
        # Count map NODES, not distinct m_eventId values. Nodes can share an
        # id (Addendum's Egypt has 44 nodes but only 40 ids) and the game UI
        # counts 44. The save only records ids, so any node whose id is
        # cleared counts as cleared.
        lv, ex = [], []
        for e in sorted((x for x in od.get('m_eventList', [])
                         if x.get('m_eventType') == 'level'),
                        key=lambda x: x['m_eventId']):
            rec = [e['m_eventId'], e.get('m_name', ''),
                   e.get('m_levelNodeType', '')]
            (ex if la_danger_room(e) else lv).append(rec)
        order += 1
        wid = str(od['m_worldId'])
        hidden = m.get('Hidden', False)

        # Two worlds can share an m_worldId (Addendum gives eighties and
        # beach both id 10). The save keys on worldId so it cannot tell them
        # apart either. Merging is the only way not to lose levels; skipping
        # the second one used to drop whole worlds from the total.
        if wid in worlds:
            cur = worlds[wid]
            if cur['counted'] and hidden:
                continue                      # never let a hidden world win
            if hidden and not cur['counted']:
                continue
            cur['nodes'] += lv
            cur['excluded'] += ex
            cur['total'] = len(cur['nodes'])
            if nm not in cur['name'].split('+'):
                cur['name'] += '+' + nm
            cur['counted'] = cur['counted'] or not hidden
            continue

        worlds[wid] = {
            'name': nm, 'code': nm, 'order': order,
            'counted': not hidden,
            'total': len(lv), 'nodes': lv, 'excluded': ex,
        }
    return {'_fingerprint': fingerprint, '_note': [
        "Generated by build_worlds.py, which overwrites this file. Do not edit.",
        "counted=false: world hidden on the map (tutorial, leftover vanilla data).",
        "excluded: Danger Rooms, which the game leaves out of its own total.",
    ], 'worlds': worlds}


def main():
    ap = argparse.ArgumentParser(description="Compute a PvZ2 mod's level counts from its OBB")
    ap.add_argument('pkg')
    ap.add_argument('--obb', help='read a local OBB file instead of going through adb')
    ap.add_argument('--url', help='read the OBB straight from a URL over HTTP Range, '
                                  'no Android device needed (used by CI)')
    a = ap.parse_args()

    if a.url:
        # Only a few scattered megabytes of a multi-gigabyte file. The
        # fingerprint uses Content-Length to spot a changed release.
        from compat import http_get
        reader = HttpReader(a.url)
        size = len(http_get(a.url, {'Range': 'bytes=0-0'}))  # probe that the range read works
        head = reader.read(0, 4)
        if head != b'1bsr':
            sys.exit(f'URL did not return an RSB archive (got {head!r}). '
                     f'Does the server support HTTP Range?')
        fp = {'source': a.url, 'size': _url_size(a.url)}
        print(f'reading {a.url}  ({fp["size"]:,} bytes) over HTTP Range')
    elif a.obb:
        reader = FileReader(a.obb)
        fp = {'source': a.obb, 'size': os.path.getsize(a.obb),
              'mtime': int(os.path.getmtime(a.obb))}
    else:
        adb = find_adb()
        dev = pick_device(adb, a.pkg)
        path, size, mtime = obb_info(adb, dev, a.pkg)
        print(f'reading {path}  ({size:,} bytes) from device {dev}')
        reader = AdbReader(adb, dev, path)
        fp = {'source': path, 'size': size, 'mtime': mtime}

    data = build(reader, fp)
    os.makedirs(WORLDS_DIR, exist_ok=True)
    out = os.path.join(WORLDS_DIR, f'{a.pkg}.json')
    json.dump(data, open(out, 'w'), indent=1, ensure_ascii=False)

    tot = sum(w['total'] for w in data['worlds'].values() if w['counted'])
    for w in sorted(data['worlds'].values(), key=lambda x: x['order']):
        mark = '' if w['counted'] else '   (hidden, not counted)'
        ex = f"  +{len(w['excluded'])} danger" if w['excluded'] else ''
        print(f"  {w['name']:<12}{w['total']:>4} levels{ex}{mark}")
    print(f'\nTOTAL: {tot} levels  ->  {out}')


if __name__ == '__main__':
    main()
